# Generated by Django 4.0.10 on 2023-02-24 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiServer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='body',
        ),
    ]
