# Generated by Django 4.0.10 on 2023-02-27 09:17

import ApiServer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiServer', '0003_object_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='body',
            new_name='dadImg',
        ),
        migrations.AddField(
            model_name='object',
            name='momImg',
            field=models.ImageField(blank=True, null=True, upload_to=ApiServer.models.upload_to),
        ),
    ]
